services:
  python:
    container_name: "python_service"
    build:
      context: "./python"
    init: true
    volumes:
      - "./python/apisource:/home/work/apisource"
    ports:
      - "8000:8000"
    working_dir: "/home/work/apisource"
    environment:
      - "TZ=Asia/Tokyo"
  node:
    image: "node:23-slim"