services:
  python:
    container_name: "python_service"
    build:
      context: "./python"
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    init: true
    volumes:
      - "./python/apisource:/app"
    ports:
      - "8000:8000"
    environment:
      - "TZ=${TZ}"
  node:
    build:
      context: "./node"
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    init: true
    volumes:
      - "./node/frontend:/app"
    ports:
      - "5173:5173"
    environment:
      - "TZ=${TZ}"
