services:
  python:
    build: "./python"
    init: true
    volumes:
      - "./python/apisource:/home/work/apisource"
    ports:
      - "8000:8000"
    working_dir: "/home/work/apisource"
    command: ["../.local/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
  node:
    image: "node:23-slim"