services:
  python:
    build: "./python"
    init: true
    volumes:
      - "./python/apisource:/home/work/apisource"
    ports:
      - "8000:8000"
    working_dir: "/home/work/apisource"
    command: ["sh", "/home/work/apisource/run_server.sh"]
  node:
    image: "node:23-slim"