name: テストをDocker Composeで実行

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeでサービスを起動してテストを実行
        run: |
          docker compose -f compose.yml -f compose.dev.yml up -d --build

      - name: Docker Composeでサービスを停止
        run: |
          docker compose down --rmi local -v