name: テストをDocker Composeで実行

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeでサービスを起動してテストを実行
        run: |
          docker compose -f compose.yml -f compose.dev.yml up -d --build

      - name: テスト完了を確認するためのコンテナのヘルスチェック
        run: |
          count=0
          until [ $(docker inspect --format='{{.State.Health.Status}}' extract-streams-web-python-1) = "healthy" ] || [ $count -eq 25 ]; do
            echo "コンテナが正常になるのを待っています... ($count/25)"
            sleep 5
            count=$((count + 1))
          done
          if [ $count -eq 25 ]; then
            echo "コンテナが指定された試行回数内で正常になりませんでした。"
          fi

      - name: テスト結果のログを表示
        run: |
          docker compose logs python

      - name: Docker Composeでサービスを停止
        run: |
          docker compose down --rmi local -v