name: テストをDocker Composeで実行

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeをセットアップ
        run: |
          docker compose -f compose.yml -f compose.dev.yml up -d --build

      - name: 必要なディレクトリを作成し権限を設定
        run: |
          docker compose exec python sh -c "mkdir -p /home/work/apisource/logs && chmod -R 700 /home/work/apisource"

      - name: コンテナ内でテストを実行
        run: |
          docker compose exec python sh /home/work/apisource/tests/run_tests.sh

      - name: Docker Composeを終了
        if: always()
        run: |
          docker compose down --rmi local -v