name: テストをDocker Composeで実行

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeでサービスを起動
        run: |
          docker compose -f compose.yml -f compose.dev.yml up -d --build

      - name: ログディレクトリを作成
        run: |
          docker compose exec python mkdir -p /home/work/apisource/logs

      - name: ファイルとディレクトリの権限を設定
        run: |
          find . -type d -exec chmod 755 {} +
          find . -type f -exec chmod 644 {} +

      - name: テストスクリプトを実行
        run: |
          docker compose exec python sh /home/work/apisource/tests/run_tests.sh

      - name: Docker Composeでサービスを停止
        run: |
          docker compose down --rmi local -v