name: テストをDocker Composeで実行

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: テストを実行
        run: |
          docker compose -f compose.yml -f compose.dev.yml up -d --build
          docker compose exec python sh /home/work/apisource/tests/run_tests.sh
          docker compose down --rmi local -v